apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: open-ads
build:
  artifacts:
    - image: ads-manager
      custom:
        buildCommand: ./gradlew :ads-manager:jibDockerBuild
        dependencies:
          paths:
            - ads-manager/*
          ignore:
            - ads-manager/build/*
    - image: ads-tracker
      custom:
        buildCommand: ./gradlew :ads-tracker:jibDockerBuild
        dependencies:
          paths:
            - ads-tracker/*
          ignore:
            - ads-tracker/build/*
  tagPolicy:
    sha256: { }
  local:
    push: false
deploy:
  helm:
    releases:
      - name: mysql
        remoteChart: oci://registry-1.docker.io/bitnamicharts/mysql
        version: 12.2.0
        namespace: mysql
        createNamespace: true
        valuesFiles:
          - k8s/mysql/values.yaml
        wait: true
      #      - name: bytebase
      #        remoteChart: https://bytebase.github.io/bytebase-1.1.1.tgz
      #        namespace: bytebase
      #        createNamespace: true
      #        valuesFiles:
      #          - k8s/bytebase/values.yaml
      - name: casdoor
        remoteChart: oci://registry-1.docker.io/casbin/casdoor-helm-charts
        version: v1.779.0
        namespace: casdoor
        createNamespace: true
        valuesFiles:
          - k8s/casdoor/values.yaml
manifests:
  rawYaml:
    - k8s/ads-manager/*
    - k8s/ads-tracker/*
