apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: open-ads
build:
  artifacts:
    - image: ads-manager
      custom:
        buildCommand: ./gradlew :ads-manager:jibDockerBuild
        dependencies:
          paths:
            - ads-manager/*
          ignore:
            - ads-manager/build/*
    - image: ads-tracker
      custom:
        buildCommand: ./gradlew :ads-tracker:jibDockerBuild
        dependencies:
          paths:
            - ads-tracker/*
          ignore:
            - ads-tracker/build/*
  tagPolicy:
    sha256: { }
  local:
    push: false
deploy:
  helm:
    releases:
      - name: casdoor
        remoteChart: oci://registry-1.docker.io/casbin/casdoor-helm-charts
        version: v1.779.0
        namespace: casdoor
        createNamespace: true
        valuesFiles:
          - k8s/casdoor/values.yaml
manifests:
  rawYaml:
    - k8s/ads-manager/*
    - k8s/ads-tracker/*
