services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    command:
      - start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8000:8080"
    volumes:
      - keycloak:/opt/keycloak/data

volumes:
  keycloak:
    driver: local
