include:
  - ./bytebase/docker-compose.yaml
  - ./casdoor/docker-compose.yaml
  - ./mysql/docker-compose.yaml

services:
  ads-manager:
    image: ads-manager:latest
    depends_on:
      - mysql
      - casdoor

  ads-tracker:
    image: ads-tracker:latest
    depends_on:
      - mysql
      - casdoor
