include:
  - ./kafka/docker-compose.yaml
  - ./keycloak/docker-compose.yaml
  - ./mysql/docker-compose.yaml

services:
  ads-manager:
    image: ads-manager:latest
    depends_on:
      - kafka
      - keycloak
      - mysql

  ads-tracker:
    image: ads-tracker:latest
    depends_on:
      - kafka
      - keycloak
      - mysql
