include:
  - ./keycloak/docker-compose.yaml
  - ./mysql/docker-compose.yaml

services:
  ads-manager:
    image: ads-manager:latest
    depends_on:
      - mysql
      - keycloak

  ads-tracker:
    image: ads-tracker:latest
    depends_on:
      - mysql
      - keycloak
