database:
  driver: mysql
  user: casdoor
  password: casdoor
  host: mysql.mysql.svc.cluster.local

service:
  port: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: casdoor.k8s.orb.local
      paths:
        - path: /
          pathType: ImplementationSpecific
