services:
  kafka:
    image: bitnami/kafka:3.9
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT_HOST://:9092,CONTROLLER://:9093,PLAINTEXT://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT_HOST://localhost:9092,PLAINTEXT://kafka:29092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - "9092:9092"
    volumes:
      - kafka:/bitnami/kafka

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    environment:
      - DYNAMIC_CONFIG_ENABLED=true
    ports:
      - "8001:8080"
    volumes:
      - kafka-ui:/etc/kafkaui
    depends_on:
      - kafka

volumes:
  kafka:
    driver: local
  kafka-ui:
    driver: local
