server:
  port: 3000

spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/ads_manager
    username: root
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/ads_manager
    user: root
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/realms/open-ads/protocol/openid-connect/certs
