server:
  port: 3000

spring:
  security:
    oauth2:
      client:
        registration:
          casdoor:
            client-id: fbaeb1e7a8895862e7a5
            client-secret: bcc1be441454b24d29471f77caecf2640b9c1580
            scope: read,write
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:3000/login/oauth2/code/casdoor
        provider:
          casdoor:
            authorization-uri: http://localhost:8000/login/oauth/authorize
            token-uri: http://localhost:8000/api/login/oauth/access_token
            user-info-uri: http://localhost:8000/api/user
            user-name-attribute: name
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/.well-known/jwks
