spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ads_manager
    username: root
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/ads_manager
    user: root
    password: password
